version: "2"
linters:
  enable:
    - revive
    - gocritic
    - unparam
    - prealloc
  settings:
    staticcheck:
      checks:
        - all
    revive:
      rules:
        - name: var-naming
          arguments:
            - []
            - []
            - - skip-package-name-checks: true
formatters:
  enable:
    - gofumpt
    - golines
  settings:
    golines:
      max-len: 120
      tab-len: 4
